Basic extrapolation of join button functionality into component
SA-BlueOcean/PetCentral pull request #52
Opened 2024-01-04 22:45 UTC by malloryporche

### src/components/Group/GroupHeader

- Removed join btn from header, imported component
- Refactored header styling **Burhan to fix**

### pages/group/index.tsx

- Added JoinBtn component, # of members

2024-01-04 22:50 UTC, burhan-syed requested changes
cleaning up layout, do not merge

2024-01-04 23:08 UTC, redconOne commented
Urge to merge rising

2024-01-05 00:41 UTC, burhan-syed commented
> Urge to merge rising

feel free to review!

2024-01-05 00:46 UTC, burhan-syed approved these changes

2024-01-05 00:57 UTC, merged